spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    database: H2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    platform: H2
    initialization-mode: always